[project]
name = "alt_data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.2.2",
    "anthropic>=0.116.0",
    "duckdb>=1.5.4",
    "fastapi>=0.139.0",
    "ipykernel>=7.3.0",
    "jinja2>=3.1.6",
    "marimo[sql]>=0.23.13",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "plotly>=6.0.0",
    "polars[pyarrow]>=1.42.1",
    "psycopg[binary]>=3.3.4",
    "requests>=2.34.2",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.50.2",
    "vl-convert-python>=1.9.0",
]
